### ISSUE TITLE
no statistics found

### ISSUE THREAD

**Issue by GitHubMe78** [bokub/ha-linky#15]
Bonjour
Depuis l'installation de l'ad on j'ai le message:

Connection with Home Assistant established
[03/12 06:26] Synchronization started for consumption data
No statistics found for PRM xx in Home Assistant
Data synchronization failed, no previous statistic found in Home Assistant
Connection with Home Assistant closed
Que dois-je faire ?
Sachant que le test fonctionne parfaitement

**Comment by bokub** [comment]
Salut, qu'appelles-tu "le test" ?

Sinon pour essayer de comprendre d'où vient le problème, tu peux:
1. Vérifier que tu as des données de consommation sur ton espace Enedis
2. Vérifier que tu arrives à récupérer ces données sur la page exemples de [Conso API](https://conso.boris.sh/exemples)

**Comment by bokub** [comment]
En l'abscence de réponse je me permet de fermer cette issue

**Comment by bokub** [comment]
Effectivement, l'add-on plante car il y a une incohérence dans des statistiques:
- Dans la liste des statistiques disponibles, il trouve l'ID de ton PRM, donc il se dit "nickel y'a déjà des données je vais synchro les jours manquants"
- Lorsqu'il cherche la dernière statistique, il n'en trouve aucune

La solution de @Sylv1F permet de faire un nettoyage proprement afin que l'add-on recommence une synchronisation complète

**Comment by Sylv1F** [comment]
> Effectivement, l'add-on plante car il y a une incohérence dans des statistiques:
> 
> * Dans la liste des statistiques disponibles, il trouve l'ID de ton PRM, donc il se dit "nickel y'a déjà des données je vais synchro les jours manquants"
> * Lorsqu'il cherche la dernière statistique insérée (pour en connaitre la date), il n'en trouve aucune
> 
> La solution de @Sylv1F permet de faire un nettoyage proprement afin que l'add-on recommence une synchronisation complète

Quelle réactivité ;-)

**Comment by bokub** [comment]
> Quelle réactivité

Et oui ! :zap: 


@Sylv1F Afin de mieux comprendre comment ce problème arrive, as-tu des pistes à partager ?
Avais-tu modifié ta BDD ? Y avait-il bien des données avant  ? Cela vient-il d'un plantage qui aurait effacé des données ? Ou d'une mise à jour de l'add-on ?

**Comment by bokub** [comment]
Ou alors j'ai peut-être une autre hypothèse:

- Au démarrage lors de la première installation, l'add-on tente une synchronisation complète mais plante pour une raison X ou Y (Enedis :angry: )
- Ensuite, tous les matins, l'add-on tente une synchronisation partielle mais ne trouve aucune donnée donc ne comprend pas ce qui lui arrive

Si mon hypothèse est bonne, il suffirait de redémarrer l'add-on pour réessayer une synchronisation complète

**Comment by GitHubMe78** [comment]
Hello Boris 
Pour ma part, autant que je me souvienne, j'avais fais un reset des données en vain.
Et effectivement l'add-on n'a jamais fonctionné chez moi.
Je me repenche sur la question après les huîtres et le foie gras

**Comment by bokub** [comment]
OK pas de soucis ! Si tu peux partager les logs au moment du reset (plus particulièrement le redémarrage juste après choisi `sync` ) ça pourrait bien aider !

**Comment by Sylv1F** [comment]
@bokub 

Dans mon cas, idem HS depuis l'installation.
C'était une primo installation de l'add-on, sur une installation HA également recente.

1. J'ai laissé 2 jours de suite le connecteur en échec, en espérant un retour à la normale => HS
2. Redémarrage Add-on => HS
3. Redémarrage HA => HS
4. Regeneration Clé ENEDIS => HS
5. Désinstallation/Reinstallation Addon => HS

**Comment by Sylv1F** [comment]
@bokub 

De mon côté plus de log dispo, simplement le log suite à reset + sync :

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM XXXXXXXXXXXXXX found in configuration for consumption
[19/12 11:21] New PRM detected, importing as much historical consumption data as possible
Successfully retrieved consumption load curve from 2023-12-12 to 2023-12-19
Successfully retrieved daily consumption data from 2023-07-15 to 2023-12-12
Successfully retrieved daily consumption data from 2023-02-15 to 2023-07-15
Successfully retrieved daily consumption data from 2022-09-18 to 2023-02-15
Successfully retrieved daily consumption data from 2022-04-21 to 2022-09-18
Successfully retrieved daily consumption data from 2021-11-22 to 2022-04-21
Successfully retrieved daily consumption data from 2021-06-25 to 2021-11-22
Successfully retrieved daily consumption data from 2021-01-26 to 2021-06-25
Cannot fetch daily consumption data from 2020-08-29 to 2021-01-26, here is the error:
Conso API a répondu avec une erreur
Code: 400
Réponse : {
    "status": 400,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "ADAM-ERR0125",
        "error_description": "The start date must be greater than the history deadline."
    }
}
Data import returned 1218 data points from 26/01/2021 to 18/12/2023
Data synchronization planned every day at 06:34:03 and 09:34:03
Connection with Home Assistant closed

**Comment by bokub** [comment]
OK ce genre de log ça veut dire que la synchro initiale s'est bien déroulée ! Tu arrives à visualiser des données dans le dashboard énergie ? Est-ce que l'ID de la statistique est bien au fortmat `linky:1345` (12345 étant ton PRM) ? 

Si tout va bien, la prochaine synchro partielle (demain matin) devait trouver la donnée du 18 décembre dans la BDD et récupérer la donnée du 19
Tu me tiens au courant ?

**Comment by Sylv1F** [comment]
J'ai les datas du 18/12
Les données journalières du 11 au 18/12 OK
![image](https://github.com/bokub/ha-linky/assets/64889671/79ae8ce0-edaf-4aa0-96e3-0135409c5c69)

Les données journalières avant le 12/12 OK mais pas de détail heure/heure (graph), simplement la data de conso de la journée
![image](https://github.com/bokub/ha-linky/assets/64889671/75f23693-82f6-4960-af2e-83381b9b11f4)

Par contre les données (graph + datas) Hebdomadaires, Mensuelles, Trimestrielles, Annuelles => OK

Pas de problème je te tiens au courant demain

**Comment by GitHubMe78** [comment]
Je vais tous desinstaller, bien effacer les data et réinstaller. 
Quel répertoire reçoit les données ?
Je vais m'assurer qu'il est bien supprimé après la desinstallation

**Comment by bokub** [comment]
C'est en base de données, normalement si ça s'efface bien tu verras plus ta statistique dans la liste en configurant le dashboard énergie

**Comment by Sylv1F** [comment]
@bokub 

Contrôle ce matin, tout fonctionne, les données du 19/12 remontent correctement

[20/12 06:34] Synchronization started for consumption data
Last saved statistic date is 18/12/2023
Successfully retrieved consumption load curve from 2023-12-19 to 2023-12-20
Data import returned 24 data points from 19/12/2023 to 19/12/2023
Connection with Home Assistant closed
