### ISSUE TITLE
Impossible de récupérer un token

### ISSUE THREAD

**Issue by Plop** [bokub/ha-linky#18]
Bonjour,

Lorsque je cherche à récupérer un token à partir du site conso.boris.sh, je suis redirigé vers le site d'Enedis, mais je ne peux pas valider de demande d'accès.

Enedis m'indique "Compteur incompatible. Il doit collecter les données listées ci-dessus", et il n'y a pas de données listées au-dessus. (cf image)
![image](https://github.com/bokub/ha-linky/assets/876470/060caee9-3202-47ca-bfb9-e99fb79a69c5)

Il m'est en revanche possible de récupérer un token en passant par d'autres services (par exemple my electrical data).

Merci d'avance

**Comment by mbourand** [comment]
Même problème chez moi, le fait qu'on ait l'air d'avoir le problème en même temps alors que je ne le vois rapporté dans aucun e autre issue me fait dire que c'est peut-être une panne côté enedis ?

**Comment by bokub** [comment]
Hello,

Le problème vient de la page de consentement, il s'agit donc un souci côté Enedis et je n'ai malheureusement pas la main dessus. 

Je t'invite à patienter quelques jours, ça avait suffit pour https://github.com/bokub/conso-api/issues/17

Par ailleurs, je remarque tu tu as posté une issue dans le mauvais repository, HA Linky c'est un add-on pour Home Assistant, alors que c'est plutôt [Conso API](https://github.com/bokub/conso-api) qui est concerné par ton problème

**Comment by Plop** [comment]
Oups désolé, comme je souhaitais configurer HA Linky et que je suivais la doc, je n'ai pas pensé qu'il s'agissait de deux choses différentes. Merci pour l'info en tout cas, je vais patienter et retenter régulièrement :)

Et merci également pour ces outils !
