### ISSUE TITLE
reinstallation et comment redemander un token

### ISSUE THREAD

**Issue by phid78** [bokub/ha-linky#20]
bonjour, suite a la mise a jour HA24.1.0, mon systeme a planté j'ai eu beau essayé de restoré des sauvegardes, rien n'y fait.
Je recommence donc sur une installation toute propre et quand j'ajoute le plugin, vais sur le conso api qui me redirige sur enedis
J'arrive sur la page deja vu sur ([issue 18](https://github.com/bokub/ha-linky/issues/18)) sauf que lui n'a pas de compteur de renseigné alors que moi si
![image](https://github.com/bokub/ha-linky/assets/147193807/ed9297d4-695e-4d1c-af46-d7bceb9126a3)

Sur mon ancienne installation tout fonctionnait bien, alors je vais dans la page de "gerer l'acces a mes données" et j'ai

![image](https://github.com/bokub/ha-linky/assets/147193807/7da5a69e-1f40-43cc-a67c-940dd3c96f91)
 (je viens d'activé la collecte horaire)

Sur la page "partage des données", je n'ai que mon fournisseur actuel, je n'ai pas de trace de mon ancienne autorisation
Ma question : dois je attendre comme la personne de l'issue 18 ou ai je quelque chose a faire pour recuperer un nouveau token ?
D'avance merci

**Comment by bokub** [comment]
Hello !

Ce n'est pas un problème avec HA-Linky donc tu ne regardes pas dans le bon repo, je t'invite à aller voir ici: 
https://github.com/bokub/conso-api/issues/26

Sinon j'ai mis un message bien voyant (cadre jaune) sur https://conso.boris.sh, je suis étonné que tu sois passé à côté

**Comment by phid78** [comment]
J'avais bien vu le cadre jaune, mais comme ca fonctionnait parfaitement, il y a encore une semaine, j'ai voulu voir si je pouvais recuperer le token, donc je suis passé outre cette info pour aller dans "gerer l'acces a mes données" en pensant soit le trouver, soit trouver l'autorisation que j'avais donné et la revoquer pour en demander une autre. 
Je pensais donc etre dans un autre cas de figure que les autres postes, mais apparement je tombe au mauvais moment ou ca bug coté enedis. 
Si je peux me permettre, il serait peut etre bon de mettre une capture dans le cadre jaune pour qu'on comprenne bien que c'est de cette page dont tu parles par page de consentement, les tetes en l'air comme moi serait plus vigilant.
Désolé pour le derangement

**Comment by bokub** [comment]
Pas de soucis, bonne soirée !

**Comment by XDECO** [comment]
Bonjour

Je souhaite utiliser HA-Linky, j'ai suivi la procédure comme décrit dans le Tuto mais je n'est pas obetnu le Token à la fin de l'enregistrement de compteur.
J'ai contacté Enedys pour leur demander le Token malheureusement la hote ligne n'a pas été capable de me renseigner de la procédure pour l'obtenir ?

Si vous savez comment le récupérer je suis preneur mais j'ai l'impression que cela n'est plus possible 

Merci pour votre aide

Cordialement

**Comment by bokub** [comment]
Salut

J'ai l'impression de radoter mais comme indiqué dans mon message juste au dessus, je t'invite à aller voir ici

https://github.com/bokub/conso-api/issues/26

Bonne soirée

**Comment by niko44** [comment]
@bokub bonjour,

Je pense qu'effectivement tout le monde a vu ce cadre jaune et nous sommes tous en phase le pb ne vient pas de l'addon en soit mais c'est juste que ça fait maintenant 2 semaines que le pb existe coté ENEDIS et toujours pas de correction.
Les vacances sont terminées mais pourtant rien ne bouge de leur coté.

**Comment by bokub** [comment]
Bonjour,

Le problème est résolu, je ferme donc cette issue
