### ISSUE TITLE
Cannot authenticate with Home Assistant

### ISSUE THREAD

**Issue by pfrenard** [bokub/ha-linky#23]
Hello, me voila de retour (Enedis a enfin réussit a créer mon PRM et la génération de token est OK)

je fais tourner HA dans un cluster kubernetes (k3s), dans un namespace dédié
j'ai : 
 - un pod homeasssistant, joignable sur http://homeassistant:8123
 - un pod linky

j'obtiens le message d'erreur suivant `Cannot authenticate with Home Assistant`
j'ai configuré la websocket comme ceci `WS_URL=ws://homeassistant:8123/api/websocket`

Depuis le pod linky quand je fais `curl http://homeassistant:8123/api/websocket` j'obtiens 
`No WebSocket UPGRADE hdr: None
 Can "Upgrade" only to "WebSocket"`

il doit y avoir une solution simple, mais je ne la vois pas ...

Merci par avance

**Comment by bokub** [comment]
Hello,

Il me semble que @Emixam91 a eu le même souci dans son issue #21

Si tu lui demandes gentiment je pense qu'il peut t'expliquer comment il l'a résolu 🙂

**Comment by Emixam91** [comment]
Bonsoir, alors oui en effet j’ai eu le même message d’erreur. 
Avez-vous essayer « WS_URL=ws:http://homeassistant:8123/api/websocket » ?
De plus il faut bien retirer les <> au niveau du token, de l’adresse et du chemin du fichier options. 
Je posterai demain la commande complète que j’ai utilisée dans mon issue.

**Comment by pfrenard** [comment]
Je viens d'essayer avec 
 - "ws:http://homeassistant:8123/api/websocket" 
 - "ws:homeassistant:8123/api/websocket"
et j'ai le message d'erreur
Error: You must specify a full WebSocket URL, including hostname. Relative URLs are not supported.

de facon assez logique la seule syntax qui semble marcher est 
 "ws://homeassistant:8123/api/websocket"
mais j'ai toujours le message "Cannot authenticate with Home Assistant"

**Comment by Emixam91** [comment]
D'accord, le token utilisé est bien le longue durée généré par Home Assistant ? 
Je vous met la commande qui a fonctionné pour moi : 
docker run -e SUPERVISOR_TOKEN='Token longue durée HA' -e WS_URL='ws:http://adresse HA/api/websocket' -v /Chemin du fichier options:/data ha-linky 
De plus pouvez-vous indiquer la commande complete que vous utilisez svp ?

**Comment by bokub** [comment]
Je trouve ça très étrange que `ws:http://` puisse fonctionner,  mais si ça marche pour toi tant mieux !

@pfrenard tu as essayé de mettre une IP (comme spécifié dans la doc) plutôt que `homeassistant` ?

**Comment by pfrenard** [comment]
Bon j'ai trouvé :)

le soucis venait d'un petit détail, dans la doc, il est précisé "<token> par le jeton d'accès Home Assistant que vous avez créé juste avant" 
j'ai été un peu vite et j'ai lu uniquement la fin de la phrase, bref c'est mieux de mettre un token généré dans home assistant :) (peut-etre rajouter "en passant par le profile home assistant")

et donc ca marche nickel.

Merci

**Comment by bokub** [comment]
J'ai justement fait attention à utiliser un mot différent ("jeton d'accès Home Assistant" vs. "token Conso API") pour éviter la confusion, mais t'as probablement raison ça doit pas être assez clair

**Comment by bokub** [comment]
Content que ce soit résolu !
