### ISSUE TITLE
Puissance maximum consommée dans la journée

### ISSUE THREAD

**Issue by guibar** [bokub/ha-linky#25]
Merci pour cet add-on que j'ai installé avec succès et qui marche bien (depuis qu'Enedis y met un peu du sien).

Est-il possible de récupérer dans home assistant la donnée quotidienne sur la puissance instantanée maximum atteinte dans la journée? 
C'est une donnée que l'on peut voir sur le site d'Enedis et qui me semble que la commande linky permet d'obtenir.

**Comment by bokub** [comment]
Effectivement, la donnée est disponible dans les données d'Enedis, mais je ne vois pas trop comment tu voudrais l'afficher dans le tableau de bord énergie

**Comment by guibar** [comment]
Merci Boris pour tout le travail fourni. 
Je ne veux pas forcement l'afficher dans le tableau de bord énergie (si ça n'est pas possible). Si j'avais accès à la donnée comme une entité, je pourrais l'afficher dans un autre tableau de bord. J'ai un contrat de 6kVA et je suis ric-rac, je dépasse même parfois. Je crois qu'il y a une certaine tolérance au dépassement. Bref, cette donnée est intéressante pour moi.

**Comment by bokub** [comment]
OK je vois, je pense que tu as besoin d'une entité dédiée, mais ce n'est pas vraiment la direction que suit ce projet qui est basée uniquement sur les statistiques.

Si tu sais coder un petit peu, je pense que tu peux créer un script bash qui appelle Conso API une fois par jour avec une automation (pas plus stp !), et qui met une entité à jour avec la valeur de la veille

**Comment by guibar** [comment]
Ok, je vois.

Je ne suis pas familier avec les contraintes du tableau de bord énergie,
mais est-ce vraiment impossible de trouver une place pour y afficher cette
variable?

**Comment by bokub** [comment]
C'était ma question initiale

**Comment by bokub** [comment]
@FFF3347 Je me permets de te répondre pareil qu'au dessus. Mon add-on synchronise de la donnée dans les tableaux de bord énergie, or je ne pense pas qu'il soit possible d'y stocker une puissance maximum journalière
