### ISSUE TITLE
Aucune remontée d'information dans HA Energy Dashboard

### ISSUE THREAD

**Issue by arthurremy** [bokub/ha-linky#27]
Bonjour,

Je tourne HomeAssistant en mode container sur mon SynologyNas en ARM64.

J'ai donc deployé ha-linky en docker container sur le meme environement que mon home assistant. J'ai suivi toute la configuration. J'ai bien mes PRMs qui remontent dans Home Assistant, par contre aucune donnée.

Alors qu'en utilisant la meme configuration (token, PRM) sur mon Mac cela fonctionne tres bien.

- Configuration Docker Compose
`# docker-compose.yml
services:
  ha-linky:
    image: ghcr.io/bokub/ha-linky-armv7
    environment:
      - SUPERVISOR_TOKEN=******
      - WS_URL=ws://192.168.1.150:8123/api/websocket
    volumes:
      - /volume1/docker/ha-linky:/data`

- Fichier de config options.json dans le folder 
`{
  "meters": [
    {
      "prm": "**********202",
      "token": "****",
      "name": "Maison Thoiry",
      "action": "sync",
      "production": false
    },
   {
     "prm": "**********631",
      "token": "****",
      "name": "Location Thoiry",
      "action": "sync",
      "production": false
   }
  ]
}`

![2024-02-25_16-35-08 (6)](https://github.com/bokub/ha-linky/assets/42027482/f888befe-a2d5-4826-b7bf-832ac171d1b0)
![2024-02-25_16-35-08 (7)](https://github.com/bokub/ha-linky/assets/42027482/a5a9be44-e0f3-4cbb-94fa-1513b52a1328)
![2024-02-25_16-35-08 (8)](https://github.com/bokub/ha-linky/assets/42027482/433c3947-e1c4-40f4-a102-372c08dd9dd2)
![2024-02-25_16-38-51](https://github.com/bokub/ha-linky/assets/42027482/1eedd8da-e2e6-4d70-9338-4fb0dd5ee60e)

Une idée de comment debug le probleme? Il ne me semble pas que ce soit un probleme de communication etant donnée que les entitées de consumption ont été créées ?

**Comment by arthurremy** [comment]
J'ai finalement réussi. Pour une raison inconnu j'ai du passer l'action en reset et repasser en sync pour que cela fonctionne.

![2024-02-25_17-02-58](https://github.com/bokub/ha-linky/assets/42027482/53b6da48-0ad9-45f5-a685-9c0349e42297)

**Comment by bokub** [comment]
Ça aurait été intéressant d'avoir les logs du premier import, mais trop tard !

Content que tu aies réussi à résoudre le problème tout seul

**Comment by arthurremy** [comment]
Je pense que c'est du au fait que lors de mon premier test j'ai mis deux PRM. Seulement le 1er PRM n'a pas de données car c'est un compteur provisoire. Et du coup je pense que ca a du faire une exception et stop le sync pour les deux. La ca fonctionne avec un seul PRM qui a des données.
