### ISSUE TITLE
Ecart d'une heure dans l'affichage de la consommation

### ISSUE THREAD

**Issue by alexsorel** [bokub/ha-linky#28]
Bonjour et un grand merci pour votre travail !
Tout fonctionne parfaitement en docker standalone.
Je constate juste une différence d'une heure entre les données Enedis, et la carte Energie dans HA : sur cette carte, toutes les données sont affichées avec 1 heure de plus. Par exemple une conso réelle sur la tranche 21-22h est reportée dans la carte Energie sur la tranche 22-23h.
A quoi cela peut-il être dû ? Un sujet de time zone ? (mais je ne vois pas où agir).
En vous remerciant par avance pour votre aide.

**Comment by bokub** [comment]
Hello,

Sur quoi te bases-tu pour connaitre la consommation "réelle" ? Sur Conso API ? L'espace client Enedis ?

As-tu vérifié ton fuseau horaire dans le menu Paramètres / Système de Home Assistant ?

**Comment by alexsorel** [comment]
Sur l'espace client EDF (equilibre.edf.fr), je suppose identique à Enedis, qui me donne la consommation par demi-heure. Et j'ai pu vérifier que c'était le bon créneau horaire de mes consos. Dans HA fuseau horaire = GMT+1 (Paris), idem dans mon conteneur TZ=Europe/Paris

**Comment by bokub** [comment]
Malheureusement je n'ai pas la configuration nécessaire pour tester le fonctionnement en standalone, donc je ne peux pas t'aider. Je laisse l'issue ouverte au cas où quelqu'un trouve la solution

Peux-tu partager quelques captures d'écran pour mettre en évidence le décalage ?

**Comment by alexsorel** [comment]
Bien sûr, voici les captures d'écran comparant EDF et HA. Les consos sont décalées d'1h dans HA.
![EDFvsHAlinky](https://github.com/bokub/ha-linky/assets/60271768/f1fc5e9a-61da-462e-8bec-fdd1bef8c5f9)

**Comment by bokub** [comment]
Ah oui effectivement c'est très très clair avec un tel exemple !

Je peux abuser et te demander le résultat au format JSON que tu peux récupérer dans [la page exemples](https://conso.boris.sh/exemples) de Conso API ?

**Comment by alexsorel** [comment]
Je ferai un nouvel essai demain, mais pour l'instant le résultat sur Conso API est malheureusement :

{
  "status": 500,
  "message": "The Enedis API returned an error",
  "error": {
    "error": "technical_error",
    "error_description": "Technical error. Please try later."
  }
}

**Comment by feiltom** [comment]
bonjour,
j'ai le même le probleme ;)
Cdt Thomas
