### ISSUE TITLE
"The Enedis API returned an error"

### ISSUE THREAD

**Issue by Ghizmo34** [bokub/ha-linky#29]
Cela fait plusieurs jours [semaine] que j'ai un retour d'erreur de type 404 : 
"Cannot fetch consumption load curve from 2024-02-20 to 2024-02-27, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}"
Suis-je le seul ?

**Comment by peter-bozovic** [comment]
Non, j'ai le même problème ... :-(

**Comment by bokub** [comment]
Vous avez pensé à regarder dans votre espace client Enedis si y'avait des données pour ces jours là ?

**Comment by peter-bozovic** [comment]
J'avais les données journaliers, mais pas des horaires.

Je viens d'activer l'option puis je vais voir dans quelques jours:
![image](https://github.com/bokub/ha-linky/assets/3381521/ab78f5c9-d432-48d5-bf4e-e10708c95e0c)

**Comment by jeandavid59** [comment]
Bonjour
J'ai le même message d'erreur
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM 14367148960217 found in configuration for consumption
[29/02 18:29] Synchronization started for consumption data
Last saved statistic date is 21/02/2024
Cannot fetch consumption load curve from 2024-02-22 to 2024-02-29, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
PRM 14276266191182 found in configuration for consumption
[29/02 18:29] Synchronization started for consumption data
Last saved statistic date is 22/02/2024
Cannot fetch consumption load curve from 2024-02-23 to 2024-02-29, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Data synchronization planned every day at 06:14:39 and 09:14:39
Connection with Home Assistant closed

si j'utilise la commande dans un "terminal" sous HA
curl -X GET \
    'https://conso.boris.sh/api/daily_consumption?prm=MON_PRM&start=2024-02-22&end=2024-02-29' \
    -H 'Authorization: Bearer MON_TOKEN'
J'obtiens 
{"usage_point_id":"MON_PRM","start":"2024-02-22","end":"2024-02-29","quality":"BRUT","reading_type":{"unit":"Wh","measurement_kind":"energy","aggregate":"sum","measuring_period":"P1D"},"interval_reading":[{"value":"14507","date":"2024-02-22"},{"value":"19530","date":"2024-02-23"},{"value":"21538","date":"2024-02-24"},{"value":"21717","date":"2024-02-25"},{"value":"19270","date":"2024-02-26"},{"value":"17995","date":"2024-02-27"},{"value":"19760","date":"2024-02-28"}]}
J'ai vérifié le PRM et le TOKEN dans mon fichier de config et c'est pareil. Le soucis est apparu avec les dernières révisions de l'appli.

Merci de votre aide

**Comment by bokub** [comment]
@jeandavid59 L'erreur qui s'affiche te dit qu'il n'y a pas de données **horaires**, et ta commande curl demande des données **journalières**.

Est-ce que dans ton espace client Enedis tu arrives à visualiser des données **horaires** ?

**Comment by jeandavid59** [comment]
Bonjour,
Je n'avais pas activé les consommations HORAIRES sur le site d'Enedis . Maintenant tout fonctionne correctement.
Merci du support.

**Comment by bokub** [comment]
@Ghizmo34 laisse moi deviner tu as aussi oublié d'activer la collecte ?

**Comment by peter-bozovic** [comment]
Je vois bien les données par demi-heure sur l'espace Enedis après l'activation de collecte horaire

Mais toujours rien du coté Home Assistant :(

Il n'y a plus d'erreur dans les logs du add-on:
![image](https://github.com/bokub/ha-linky/assets/3381521/4edcffc0-62da-4eae-90ee-a7e967debdb2)

Mais je ne vois toujours rien du coté dans le suivi "Energy":
![image](https://github.com/bokub/ha-linky/assets/3381521/710b79b1-7717-4067-9974-8ac33fc953a3)

J'ai désinstallé vendredi le plugin pour tout réinstaller et tout reconfiguré !
Quelque chose aurai du remonter en 2 jours ?
Ou j'ai loupé un paramétrage quelque part ? :(

**Comment by bokub** [comment]
Tu regardes bien la journée du 2 mars dans ton dashboard energy ?

**Comment by peter-bozovic** [comment]
Ah, je ne voyais pas qu'on pouvait changer la date  :)
J'ai trouvé l'option en haut et je vois bien les données des jours précédents !

Dernier élément serait d’intégrer les couts, mais j'ai vu que tu avait essayé d'en discuter sur les forums HA sans de réponse claire :(
Comme toutes les solutions que j'ai pu trouver semblent trop compliquées pour ma connaissance Noob de HA, on va faire sans pour l'instant ...

Par rapport au plugin, je dirais juste que ça pourrait être utile de préciser dans la documentation qu'en plus du compte Enedis et la clé API, il faut passer par les options pour activer le suivi par horaire !

Sinon c'est TOP ! Merci :)

**Comment by bokub** [comment]
> Par rapport au plugin, je dirais juste que ça pourrait être utile de préciser dans la documentation qu'en plus du compte Enedis et la clé API, il faut passer par les options pour activer le suivi par horaire !

Oui ça y est déjà

**Comment by gpion** [comment]
J'ai le mème problème :
```
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
```

Et sur mon compte Enedis la collecte de données horaires est bien activée

**Comment by bokub** [comment]
@gpion Pour quelle période as-tu cette erreur ? As-tu vérifié si tu voyais des données pour la période en question sur ton espace client Enedis ?

**Comment by gpion** [comment]
> @gpion Pour quelle période as-tu cette erreur ? 

journée d'hier : 
`cannot fetch consumption load curve from 2024-03-21 to 2024-03-22:`

> As-tu vérifié si tu voyais des données pour la période en question sur ton espace client Enedis ?

A oui zut, _"Données indisponibles"_ depuis 00:00 (les jours précédents sont OK)
Faut les prévenir ou simplement attendre ?

**Comment by bokub** [comment]
Tu peux les prévenir mais à mon avis tu perds ton temps... Sinon tu peux attendre quelques jours voir si le problème persiste, ou si ça concerne juste la journée d'hier.

**Comment by gpion** [comment]
Alors que j'étais en chat avec un conseiller, j'ai dupliqué l'onglet et les données sont apparues

**Comment by gpion** [comment]
Alors que j'étais en chat avec un conséiller, j'ai dupliqué l'onglet et les données sont apparues
