### ISSUE TITLE
Consommation horaire pour les données historiques

### ISSUE THREAD

**Issue by Nitrouze** [bokub/ha-linky#3]
Bravo et merci pour ce addon qui devrait intéresser pas mal de monde (de part sa simplicité de mise en œuvre notamment). 

Une remarque/suggestion ...

Il est dommage de n'avoir qu'une seule semaine de détail de la consommation (via le premier import).
J'imagine bien que la charge est lourde pour ta passerelle de remonter tout l'historique d'un coup mais ...
Serait-il possible de récupérer plus d’antériorité au fur et à mesure des imports suivants (par ex: recup dune semaine supplémentaire chaque jour)  ?

**Comment by bokub** [comment]
Salut, et merci !

Non ce n'est pas prévu, et ce serait assez compliqué techniquement car il faudrait réussir à
- trouver les lignes correspondant à la dernière plage de statistiques quotidienne en allant lire chaque heure de chaque journée dans le passé (lourd pour ton serveur home assistant)
- effacer ces statistiques mêmes si elles sont en plein milieu d'autres (ça peut potentiellement péter toutes les statistiques qui se trouvent après le trou)
- les remplacer par des statistiques détaillées en supposant qu'elle sont exactement égales aux statistiques quotidiennes au Wh près

En fait, Home assistant n'est pas vraiment prévu pour ça: chaque ligne en base de données doit contenir la somme totale depuis le début de cette statistique au risque d'avoir des statistiques toutes pétées, donc effacer des statistiques au milieu est assez risqué. 

C'est pour ça que ce module ne supporte que 2 actions:
- Tout effacer
- Ajouter des statistiques dont la date se trouve **après** la dernière ligne insérée

De plus, même si en mettant ta solution en place la charge serait effectivement étalée, ça reste 8 * 48 = 384 lignes récupérées **tous les jours** au lieu de juste 48 lignes (soit 8x plus de charge)

Je comprends bien que ça te ferait plaisir de façon individuelle, mais si j'ajoute cette fonctionnalité pour tout le monde je me retrouve avec 8x plus de charge quotidienne sur mes serveurs

Étant donné que je fournis déjà le fruit de mon travail + mes serveurs gratuitement à n'importe qui sans rien demander en retour, je préfère rester économe sur les ressources :slightly_smiling_face:

**Comment by NZX-DeSiGN** [comment]
Hello,

Je te remercie également pour cet addon que je recherchais depuis longtemps, ça fonctionne vraiment bien !

J'ai trouvé une solution pour importer les anciennes statistiques horaires sans surcharger ton API : l'export CSV depuis le site de Enedis !

J'ai implémenté un prototype, mais il reste à faire quelques ajustements pour l'intégrer de façon propre et officielle (je ne suis pas un spécialiste Typescript, Docker, addon HA, donc j'ai pas mal galéré ...)

Commit : https://github.com/bokub/ha-linky/compare/master...NZX-DeSiGN:ha-linky:csv_import

Il suffit ensuite de créer un fichier CSV `/config/linky/history.csv` qui contient juste 2 colonnes (date et valeur en watt) :
```csv
2023-10-11T00:30:00+02:00;226
2023-10-11T01:00:00+02:00;268
2023-10-11T01:30:00+02:00;68
```

J'ai remarqué par contre chez moi que avant le 27-02-2022 Enedis n'a enregistré le détail horaire, j'ai donc combiné plusieurs exports CSV depuis leur site pour avoir un historique complet !

**Comment by bokub** [comment]
Hello @Nitrouze !

Je viens de sortir la version `1.4.0`, dans laquelle tu peux désormais importer tout ton historique avec une précision horaire, en passant par un fichier CSV téléchargeable sur ton espace client Enedis :partying_face: 

Merci @NZX-DeSiGN pour l'idée :pray: 

Bonne journée !

**Comment by NZX-DeSiGN** [comment]
@bokub super, il est vraiment top ton addon !
