### ISSUE TITLE
Ajout dans HACS?

### ISSUE THREAD

**Issue by wsw70** [bokub/ha-linky#32]
J'utilise HA via sa version docker - et donc pas de HAOS et ses add-ons.
J'ai vu qu'il y avait une version standalone avec un container à côté - est-ce qu'il y a une raison pour ne pas utiliser HACS?

**Comment by bokub** [comment]
Sauf erreur de ma part, HACS c'est pour les cartes Lovelace et les intégrations, mon add-on n'est ni l'un ni l'autre donc je ne pense pas qu'il ait sa place

**Comment by wsw70** [comment]
Ah pardon - je ne me suis pas rendu compte que c'est un add-on (j'utilise HA dans un containeur, il n'y a pas d'add-ons). Désolé.
