### ISSUE TITLE
Impossible d'importer un csv sur docker

### ISSUE THREAD

**Issue by etiennec78** [bokub/ha-linky#33]
Bonsoir,
Merci pour cette extension Home Assistant très pratique !
Cependant, étant donné que je fais tourner ha-linky sur Docker, il m'est impossible d'importer mon propre csv. J'obtiens toujours d'erreur : Cannot find folder "/addon_configs/cf6b56a3_linky".
Serait il possible d'utiliser un chemin relatif au lieu d'un absolu ?

Encore merci pour votre travail !
Etienne

**Comment by bokub** [comment]
Hello !

Si si c'est possible bien que ce ne soit pas documenté.

Stocke ton fichier CSV dans un dossier sur ta machine, puis fais un volume vers un dossier `/config` dans le conteneur

Par exemple: `-v ~/mon-dossier:/config`
