### ISSUE TITLE
Pas de remontée des données Linky

### ISSUE THREAD

**Issue by kikipointcom** [bokub/ha-linky#34]
Bonjour, j'ai suivi ton tuto  et j'ai une erreur :
```
[28/03 08:14] Synchronization started for consumption data
Last saved statistic date is 27/03/2024
Everything is up-to-date, nothing to synchronize
Data synchronization planned every day at 06:38:28 and 09:38:28
Connection with Home Assistant closed
```
Le token est nickel car dans la page exemple que tu donnes, j'ai pu voir les données ?
Peut-être ais-je des prérequis à installer ou autre !
Merci

**Comment by bokub** [comment]
Salut

Je comprends pas, c'est quoi le problème ?

**Comment by kikipointcom** [comment]
Le soucis, c'est qu'aucune remontée ne se fait dans le tableau de bord Energie !
Merci à toi

**Comment by bokub** [comment]
Aucune remontée, ou pas de remontée pour **aujourd'hui** ? C'est possible d'avoir un screenshot sur la semaine ?

**Comment by kikipointcom** [comment]
Aucune remontée

**Comment by kikipointcom** [comment]
Config intégration linky:

prm: "09XXXXXXXXXXXX"
  token: >-
    eyJhbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx2LQ84g3-Tk1u8EU
  name: Linky consumption
  action: sync
  production: false

**Comment by bokub** [comment]
Le log de l'add-on indique clairement qu'il a trouvé des données sur la journée du 27 mars... Tu es certain d'avoir bien configuré ton dashboard énergie ?

**Comment by bokub** [comment]
Non mais y'a aucun problème avec l'add-on, tu dis "j'ai une erreur" mais non y'a aucune erreur, le log te dit juste que toutes les données sont déjà à jour donc il n'y a rien à faire

**Comment by kikipointcom** [comment]
Ok, je vais regarder la configuration du dashboard de plus près.merciChristian Leclerc
