### ISSUE TITLE
Message : Data synchronization failed, no previous statistic found in Home Assistant

### ISSUE THREAD

**Issue by JNoVernay** [bokub/ha-linky#35]
Bonjour,
J'ai une configuration sans production, un setup plutôt simple donc et le retour suivant :
_s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM XXXXXXXXXXXXXX found in configuration for consumption
[01/04 08:14] Synchronization started for consumption data
No statistics found for PRM XXXXXXXXXXXXXX in Home Assistant
Data synchronization failed, no previous statistic found in Home Assistant
Data synchronization planned every day at 06:25:18 and 09:25:18
Connection with Home Assistant closed_
J'ai essayé de réinstaller le module, même résultat depuis 3 jours...
Le test avec "conso API" fonctionne parfaitement. 
Je suis donc à court d'idée sur ce que j'ai loupé.
Merci de votre aide,
JNoël

**Comment by bokub** [comment]
Salut Jean-Noël

Fais un reset des donnés (explications détaillés dans le README) et refais une synchronisation de zéro, ça devrait régler le problème

**Comment by JNoVernay** [comment]
Merci Boris ! 
Le problème est réglé.
Top !
