### ISSUE TITLE
Merci !

### ISSUE THREAD

**Issue by jto2000** [bokub/ha-linky#36]
Bonjour,

Juste un grand merci pour ce repo. La documentation hyper claire est parfaite ! Elle m'a permis de faire fonctionner le tout en standalone (non sans m'y casser quelques dents...) mais surtout de m'accompagner vers un peu plus d'autonomie sur le sujet ! Franchement chapeau !
Si jamais il y a une option "simple" pour récupérer une conso professionnelle sur le site Enedis, cela m'intéresse :)

Un toulousain !

**Comment by bokub** [comment]
Avec grand plaisir ! 

Pas possible pour la conso professionnelle en revanche, l'api d'Enedis que j'utilise ne le permet pas.

**Comment by jto2000** [comment]
Ça marche c'est noté :)
Bonne continuation !

**Comment by smougenot** [comment]
Merci beaucoup pour cette intégration
