### ISSUE TITLE
Plus de données depuis le 5 avril 

### ISSUE THREAD

**Issue by hombre-13hb** [bokub/ha-linky#39]

**Comment by hombre-13hb** [comment]
Hello

voici le message d’erreur 

[08/04 09:05] Synchronization started for production data
Last saved statistic date is 04/04/2024
Cannot fetch production load curve from 2024-04-05 to 2024-04-08, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !


merci

**Comment by Thomas-lhuillier** [comment]
Même symptôme de mon côté.

**Comment by fufurax** [comment]
Idem chez moi :/

```
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
```

**Comment by bokub** [comment]
L'erreur vient d'enedis, je ne peux absolument rien faire pour vous, j'en suis navré !

**Comment by fufurax** [comment]
> L'erreur vient d'enedis, je ne peux absolument rien faire pour vous, j'en suis navré !

Ok, c'est général visiblement ? On a quelque chose à faire de notre côté avec Enedis? 
Merci

**Comment by bokub** [comment]
> On a quelque chose à faire de notre côté avec Enedis?

Vous pouvez commencer par regarder sur votre espace client Enedis si y'a des données horaires ou non pour ces jours là

**Comment by fufurax** [comment]
> > On a quelque chose à faire de notre côté avec Enedis?
> 
> Vous pouvez commencer par regarder sur votre espace client Enedis si y'a des données horaires ou non pour ces jours là

J'ai bien des données dans EDF & Moi

**Comment by Thomas-lhuillier** [comment]
Chez moi retour à la normale ce matin.

**Comment by hombre-13hb** [comment]
Idem, je clôture

**Comment by hombre-13hb** [comment]
.
