### ISSUE TITLE
Infos revente?

### ISSUE THREAD

**Issue by rpouetpouet** [bokub/ha-linky#4]
Hi! Merci pour ce plugin qui arrive à point nommé.
Tout remonte parfaitement concernant la consommation, y aurait-il moyen de récupérer également les infos de revente? (Production solaire...)
Merci d'avance pour ta réponse

**Comment by bokub** [comment]
Bonjour,

Oui c'est possible, mais il faut que je trouve le temps pour le coder ! (ou que quelqu'un m'aide à le faire)

**Comment by bokub** [comment]
Salut, c'est désormais possible depuis la version 1.2.0 !

Bonne journée

**Comment by emylive** [comment]
Merci beaucoup!! Ca fonctionne super bien!
