### ISSUE TITLE
Demande d'un débutant

### ISSUE THREAD

**Issue by NumeroDixSept** [bokub/ha-linky#41]
Bonjour,

Je suis relativement nouveau sur HomeAssistant et je viens de découvrir le plugin qui m'a grandement aidé à récupérer les informations nécessaires sur ma consommation électrique via Linky. Je tiens à exprimer ma gratitude pour le travail accompli, c'est vraiment un outil utile !

Cependant, en explorant d'avantage les possibilités offertes par HomeAssistant, je me suis demandé s'il était possible de récupérer les statistiques créées par votre plugin et de les intégrer dans Node-RED. J'aimerais utiliser ces données dans mes automatisations et analyses supplémentaires.

Je me demandais donc s'il existe déjà une méthode ou une configuration spécifique pour exporter ces statistiques vers Node-RED, ou si vous pourriez me donner quelques conseils sur la façon de procéder. Je suis ouvert à toute documentation ou ressource que vous pourriez recommander pour m'aider dans cette tâche.

J'ai vu qu'une demande (presque identique à la mienne) ete déjà ouverte : [ issues 26 ](https://github.com/bokub/ha-linky/issues/26)

Merci d'avance pour votre aide et votre temps précieux !

**Comment by bokub** [comment]
Salut !

Ravi que mon outil te plaise, mais malheureusement je ne vais pas pouvoir t'aider. À vrai dire je ne sais même pas ce qu'est Node RED...

**Comment by NumeroDixSept** [comment]
Hello ! 

Pas de soucis merci ^^ 
(PI : NodeRed c'est du "lowcode" à base de tuile avec du code js a la scratch) 

Je close l'issue
