### ISSUE TITLE
Error 500: API Enedis

### ISSUE THREAD

**Issue by CharlesHarroch** [bokub/ha-linky#44]
Tout d'abord merci beaucoup pour le travail réalisé.
Je rencontre de mon coté une erreur 500 coté serveur Enedis. Je sais que cela ne viens pas du plugin directement, mais j'aimerai savoir si un utilisateur à rencontré le meme  probleme et à trouvé une solution.

Pour information j'ai bien fais un reset des data dans la configuration du plugin. J'ai régénéré un nouveau token, vérifié les autorisation de partage chez Enedis, et tout semble ok.

Voila les logs : 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM ************ found in configuration for consumption
[29/04 21:01] New PRM detected, historical consumption data import is starting
Found 0 CSV file in /addon_configs/cf6b56a3_linky
Cannot fetch consumption load curve from 2024-04-22 to 2024-04-29, here is the error:
Conso API a répondu avec une erreur
Code: 500
Réponse : {
    "status": 500,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "technical_error",
        "error_description": "Technical error. Please try later."
    }
}
Cannot fetch daily consumption data from 2023-11-02 to 2024-04-29, here is the error:
Conso API a répondu avec une erreur
Code: 500
Réponse : {
    "status": 500,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "technical_error",
        "error_description": "Technical error. Please try later."
    }
}
Data import returned nothing !
Data synchronization planned every day at 06:20:29 and 09:20:29
Connection with Home Assistant closed`

Merci d'avance pour votre aide.

**Comment by Vincenzoz59** [comment]
Bonjour depuis 2 jours j'ai également l'erreur 500, pourtant j'ai bien des données qui remontent sur hellowatt ou beem 
Cela fonctionnait depuis plusieurs mois.

**Comment by bokub** [comment]
Salut,

Si Enedis rencontre une erreur technique je ne peux rien y faire et vous non plus, il va falloir être patient...

**Comment by Vincenzoz59** [comment]
> Salut,
> 
> Si Enedis rencontre une erreur technique je ne peux rien y faire et vous non plus, il va falloir être patient...

Je me demande si c'est pas lié au fameux bug mondial 😕

**Comment by JC38** [comment]
Bonjour,
Idem chez moi

> Conso API a répondu avec une erreur
Code: 500
Réponse : {
    "status": 500,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "technical_error",
        "error_description": "Technical error. Please try later."
    }
}
Data import returned nothing !

Enedis a confirmé être impacté mais sans donner les détails
[https://www.ledauphine.com/science-et-technologie/2024/07/19/tf1-fnac-quelles-sont-les-entreprises-francaises-touchees-par-la-panne-mondiale](url)

**Comment by andrezstar** [comment]
Même problème
Vous n'avez pas eu de news de la part d'enedis?
J'ai ouvert un CASE chez eux
