### ISSUE TITLE
Usage sans API (mode régie)

### ISSUE THREAD

**Issue by j3r3m067** [bokub/ha-linky#45]
Bonjour
Dans certains cas, les linky sont en mode régie, ce qui signifie qu’Enedis n’a pas les données.
Est-il possible de fonctionner avec ce module mais en mode import journalier? (En essayant de récupérer le fichier de la veille envoyé par mail…)

Ou essayé faire un mode « régie » pour récupérer par curl sur le portail de la regie les données de la veille?

un compteur régie est un compteur avec une (ou plusieurs) lettre(s) dans le PDL, ce qui bloque l’ajout sur le portail Enedis qui demande que des chiffres.

Bonne journée

**Comment by bokub** [comment]
Salut,

Non en l'état, cet add-on ne pourra pas fonctionner avec tes contraintes, il faudrait que tu fasses un fork et que l'adaptes à tes besoins

Bonne journée !

**Comment by j3r3m067** [comment]
Ça marche ;)
Un conseil pour dev depuis ce module et le tester ?

**Comment by bokub** [comment]
Oui, tu peux lire la [doc de Home Assistant](https://developers.home-assistant.io/docs/add-ons) si tu n'as jamais développé d'add-on, et le fichier [CONTRIBUTING.md](https://github.com/bokub/ha-linky/blob/master/CONTRIBUTING.md) qui explique comment faire pour HA-Linky spécifiquement

**Comment by bokub** [comment]
Bon courage ! :sweat_smile:
