### ISSUE TITLE
Répertoire d'import d'historique en mode image docker

### ISSUE THREAD

**Issue by otheym84** [bokub/ha-linky#46]
Bonjour,

Merci pour le module qui est bien pratique.

J'ai construit une image HA-Linky standalone, j'ai bien réussi à la démarrer.
Par contre l'import de l'historique horaire est un peu capricieux.
J'ai été obligé de monter deux volumes dans /config et /addon_configs/cf6b56a3_linky pointant sur mon répertoire d'historique.

D'après le code, il y a deux répertoires référencés :
https://github.com/bokub/ha-linky/blob/bf9ff8e81eb5c0cfcafc43a93c839b48b3e724bd/src/history.ts#L7-L8

Dans la suite du code, on trouve des lignes perturbantes :
https://github.com/bokub/ha-linky/blob/bf9ff8e81eb5c0cfcafc43a93c839b48b3e724bd/src/history.ts#L11-L12

Ne vaudrait-il pas mieux tout homogénéiser sur /addon_configs/cf6b56a3_linky et oublier /config ?

Je peux faire un PR dans ce sens mais je n'ai pas l'historique du module en tête.

**Comment by bokub** [comment]
Salut !

Pour l'import du fichier CSV tu trouveras la solution dans l'issue #33

Malheureusement je ne peux pas choisir les dossiers, sinon je t'assure que j'aurais choisi quelque chose de moins compliqué

C'est le système d'addons de Home Assistant qui fait le mapping entre dossier extérieur et dossier dans le conteneur, et ce mapping n'est pas configurable

Bonne journée!

**Comment by otheym84** [comment]
Merci pour le retour
