### ISSUE TITLE
Linky - Graphique Statistic - Arrondir Valeurs des Ordonnées

### ISSUE THREAD

**Issue by aigle1234** [bokub/ha-linky#48]
Bonjour,

Merci pour le partage de cet addon :)
J'utilise la carte statistics-graph pour l'affichage des valeurs du Linky, et recherche un workaround pour avoir les valeurs de l'axe des ordonnées arrondies (c'est à dire faire disparaitre le ",000") ex :
![image](https://github.com/bokub/ha-linky/assets/48964174/5e9a988c-14d4-4b1c-bf96-6510e2f0755a)

```
chart_type: bar
period: day
type: statistics-graph
entities:
  - entity: linky:xxxxxxxxxxxxxxxxx
stat_types:
  - change
days_to_show: 7
```

Auriez vous un workaround à proposer ?

**Comment by bokub** [comment]
Salut !

Les données sont déjà arrondies, `20,000` en anglais c'est l'équivalent de `20 000` en France, et non pas de `20,000` qui s'écrirait `20.000` en anglais.

**Comment by aigle1234** [comment]
Bonjour,
Bien vu merci !
Je n'avais pas vu que l'unité était en Wh et non kWh sur le graphique.
Savez-vous si c'est possible d'afficher en kWh dans le statistic graph ?

**Comment by bokub** [comment]
Non, je ne sais pas comment faire, désolé
