### ISSUE TITLE
Fuseau horaire (docker standalone)

### ISSUE THREAD

**Issue by Bigsmooth68** [bokub/ha-linky#54]
J'ai constaté un décalage de 2 heures sur les graphs:
- home assistant:
![2024-07-09 12_32_41-Énergie – Home Assistant](https://github.com/bokub/ha-linky/assets/57505439/bc31797c-a0be-44ef-8b7b-f81b086892bd)
- enedis:
![2024-07-09 12_32_54-Suivre mes mesures – Espace Particulier](https://github.com/bokub/ha-linky/assets/57505439/5ffb70bf-4047-4321-ac56-fc1f72df4eb5)

J'ai détecté cela avec le chauffe-eau qui se mets en route aux heures creuses (autour d'1h30 le matin).
Si j'ajoute la variable d'environement **TZ** à mon conteneur, cela règle le pb (avec un reset des stats d'abord).

A ajouter dans la doc, peut être ?

**Comment by bokub** [comment]
Oui bonne idée

Tu veux faire une pull request ?

**Comment by Bigsmooth68** [comment]
ok.
Je vais voir si ca fonctionne avec le volume aussi (/etc/timezone).

**Comment by bokub** [comment]
Corrigé par #55
