### ISSUE TITLE
Récuperer la valeur d'une stat Linky dans une notification

### ISSUE THREAD

**Issue by JC38** [bokub/ha-linky#56]
Bonjour,

J'ai bien compris que ce add-on ne créait pas d'entités qu'on pouvait interroger pour avoir des valeurs mais quelqu'un sait-il s'il est possible de récupérer la valeur d'une statistique dans une notification ?
Je m'envoie chaque jour un récap de chiffres clé de la journée passée, mais pour l'instant, je n'arrive pas à récupérer la valeur de la conso Linky dans une notification mail, sms ou autre. J'arrive juste à la voir via une carte.

**Comment by bokub** [comment]
Salut

Je crois qu'un utilisateur a réussi à faire cela en utilisant un SQL sensor

https://forum.hacf.fr/t/add-on-pour-compteurs-linky/27608/184

**Comment by JC38** [comment]
Merci pour la réponse et également pour l'add-on. Je vais suivre la piste indiquée.
