### ISSUE TITLE
Erreur dans l'aide

### ISSUE THREAD

**Issue by stbitw** [bokub/ha-linky#59]
Bonjour,

Désolé si je poste au mauvais endroit 🤪

Avec la mise à jour 1.5.0 j'ai constaté une erreur, sauf erreur, dans l'aide :

<img width="707" alt="2024-07-23 17 40 59 - GitHub - bokub_ha-linky_ 📊 Home Assistant add-on for Linky smart meters — Mozil" src="https://github.com/user-attachments/assets/5dd747c8-415d-49a1-b2e3-ee55eeae6a3c">

Il me semble que la logique a été inversée, aucun n'est optionnel sauf `price` 🙃

Merci encore pour ce super plugin 👍🏻‍

**Comment by stbitw** [comment]
Je crois que j'ai commis une erreur, ce tableau ne concerne que price et les optionnels oups 😅

Je viens de comprendre ****

**Comment by stbitw** [comment]
💩

**Comment by bokub** [comment]
Tu trouves que ce serait plus clair si la colonne s'appelait "obligatoire"?

**Comment by stbitw** [comment]
Non non, j'ai juste lu trop vite, je n'ai compris qu'après avoir posté que j'étais dans une nouvelle section de l'aide dédiée à ce nouveau paramètre price et SES options, moi qui voulait aider  🤣

Par contre j'en profite, là je suis sûr de mon coup, on dit "la marche à suivre" car "la démarche" est plutôt la façon de marcher ou encore le fait de faire une action comme aller à la mairie...

"La marche à suivre" est une locution nominale, c'est la méthode utilisable pour parvenir au but fixé.

J'espère que j'ai pu aider au moins sur un truc 😜

**Comment by bokub** [comment]
J'ai pas compris, c'est où que tu as vu "la démarche"?

**Comment by bokub** [comment]
Trouvé et corrigé ! Merci

**Comment by stbitw** [comment]
Encore merci à toi !
