### ISSUE TITLE
Image not found on Pi3 HA OS

### ISSUE THREAD

**Issue by mysiki** [bokub/ha-linky#6]
Hello,

Sur HA os (last version) installé sur Rasp Pi3+ j'ai une erreur d'image inexistante. 

Can't install ghcr.io/bokub/ha-linky-aarch64:1.1.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/bokub/ha-linky-aarch64:1.1.0/json: Not Found ("No such image: ghcr.io/bokub/ha-linky-aarch64:1.1.0")

Je ne peux pas la build moi meme car j'ai pas l'arg du FROM.

**Comment by bokub** [comment]
Et est ce que tu arrives à faire un `docker pull ghcr.io/bokub/ha-linky-aarch64:1.1.0`?

**Comment by mysiki** [comment]
alors j'arrive a pull mais en plus l'image était bien presente sur mon pi 

```
 docker pull ghcr.io/bokub/ha-linky-aarch64:1.1.0
1.1.0: Pulling from bokub/ha-linky-aarch64
Digest: sha256:140fca393a84aca03a1f601caa8ffb1e6210c970e365671cd7e3225346eeb4a1
Status: Image is up to date for ghcr.io/bokub/ha-linky-aarch64:1.1.0
ghcr.io/bokub/ha-linky-aarch64:1.1.0
```

**Comment by mysiki** [comment]
fausse alerte, l'addon semble mtn installé ... Je pense que comme le pi est pas veloce, j'ai pris des timout durant le pull de l'image. 
j'ai retanté l'installe pls fois, il a finit par y arriver

**Comment by mysiki** [comment]
And it work ! Merci, je ferme le ticket, désolé pour le bruit.
