### ISSUE TITLE
Documentation import CSV

### ISSUE THREAD

**Issue by alexandrebaldinho** [bokub/ha-linky#60]
Bonjour,

J'ai suivi la procédure d'import CSV, je possède une HA Green.
Le menu n'est pas le meme que dans la procédure. 
Et je ne peux pas remonter plus haut que le répertoire /homeassistant
![2024-07-25 12-09-27](https://github.com/user-attachments/assets/ba7885a3-6296-48d4-bb8e-7b0e1c627faf)

**Comment by bokub** [comment]
Salut Alexandre,

Es-tu certain d'avoir effectué cet étape ?

> Dans la configuration de l'add-on , désactivez l'option "Enforce Basepath", puis enregistrez

**Comment by alexandrebaldinho** [comment]
Pardon....
