### ISSUE TITLE
Ajout des couts dans home assistant

### ISSUE THREAD

**Issue by profusse** [bokub/ha-linky#61]
Bonjour à tous

Je viens d'installer la mise a jour 1.5.0 et j'ai ajouté les couts dans la configuration de ha-link mais je ne vois pas quel sensor ajouter à home assistant pour que les prix s'affiche dans la carte energy. Je précise que les relever se font correctement tous les jours.

Voici les paramètres de l'intégration:
meter:

- prm: "XXXXXXXXXXXXXXXX"
  token: >-
    ***TOKEN***
  name: Linky consumption
  action: sync
  production: false

cost:

- price: 0.18156
  after: "01:04"
  before: "07:04"
- price: 0.18156
  after: "15:04"
  before: "17:04"
- price: 0.2448
  before: "01:04"
- price: 0.2448
  after: "07:04"
- price: 0.2448
  after: "17:04"

Merci de votre aide.

**Comment by po8rewq** [comment]
Logiquement le calcul (et la création du sensor) se fera lors du prochain import (cette nuit). Sinon tu reset, au choix

**Comment by yAgeron** [comment]
Hello!
L'entité "Consomation Linky (costs)" est apparu après un premier relever suite à la mise à jours.

**Comment by profusse** [comment]
Salut

Oui effectivement tout est parfait.
