### ISSUE TITLE
"no measure found for this usage point"

### ISSUE THREAD

**Issue by zulufoxtrot** [bokub/ha-linky#64]
Hello!

Je ne parviens pas à récupérer les données de mon compteur Linky avec le plugin.

Voici mes logs:

```json
HA Linky is starting
Connection with Home Assistant established
PRM 25645441345540 found in configuration for consumption
[29/07 20:42] Synchronization started for consumption data
Last saved statistic date is 27/07/2024
Cannot fetch consumption load curve from 2024-07-28 to 2024-07-29, here is the error:
Conso API a répondu avec une erreur
Code: 404
Réponse : {
    "status": 404,
    "message": "The Enedis API returned an error",
    "error": {
        "error": "no_data_found",
        "error_description": "no measure found for this usage point"
    }
}
Data import returned nothing !
Data synchronization planned every day at 06:23:27 and 09:23:27
Connection with Home Assistant closed
```

En faisant quelques recherches, cette erreur semble provenir de l'API d'Enedis.

Alors, je ne sais pas exactement quelle requête le plugin fait, mais en tout cas, en faisant des requêtes directement, ça fonctionne:

```bash
 curl -X GET "https://conso.boris.sh/api/daily_consumption?prm=25645441345540&start=2024-07-28&end=2024-07-29" \
     -H "Authorization: Bearer mon_token"
```

réponse:
```json
{"usage_point_id":"25645441345540","start":"2024-07-28","end":"2024-07-29","quality":"BRUT","reading_type":{"unit":"Wh","measurement_kind":"energy","aggregate":"sum","measuring_period":"P1D"},"interval_reading":[{"value":"12892","date":"2024-07-28"}]}
```

À noter que j'ai activé ma ligne il y a un peu plus d'un mois et que je rencontre d'autres problèmes: ni mon fournisseur d'énergie, ni Hellowatt ne parviennent à récupérer la conso jour, alors qu'elle est activée. Sur l'espace client d'Enedis, je la vois bien.

Une idée pour résoudre mon problème? 😇

**Comment by zulufoxtrot** [comment]
Un peu plus de détails:
Voilà ce que je vois sur mon espace Enedis:

<img width="740" alt="Screenshot 2024-07-29 at 20 53 57" src="https://github.com/user-attachments/assets/3d5549aa-89f3-4e5b-bd50-b85f07cc2fb5">

Je ne sais pas la différence entre "enregistrement" et "collecte". Quoi qu'il en soit, si j'essaie d'activer "collecte" j'obtiens cette erreur: 

<img width="591" alt="Screenshot 2024-07-29 at 20 54 56" src="https://github.com/user-attachments/assets/76e8b636-519f-4da7-90c4-3ea94ec9a660">

Bon, y'a sûrement un problème du côté d'Enedis, mais ça n'explique pas pourquoi ma requête fonctionne en direct mais pas dans le plugin 🧐

**Comment by bokub** [comment]
Salut,
Tes tests en curl sont sur des données quotidiennes alors que HA Linky récupère des données horaires, donc c'est normal que tu aies des résultats différents.

Il faut que tu actives la collecte, comme expliqué dans ma documentation

**Comment by zulufoxtrot** [comment]
Oups, j'avais zappé cette étape.

Ouais du coup c'est clairement de leur côté, je vais fermer ce ticket.

Merci!
