### ISSUE TITLE
Price is not correctly shown in the energy dashboard

### ISSUE THREAD

**Issue by MaJerle** [bokub/ha-linky#65]
This addon is a great work - thanks for making and maintaining it.

I successfully integrated the addon and I set the price as, which presents `EUR cents 24.23`:

```yaml
- price: 0.2423
```

but in my dashboard, consumption and price seems to be set to `EUR 1/kWh`.
![image](https://github.com/user-attachments/assets/0546f747-cfcb-4c8b-ac14-af3f1527672c)

What am I doing wrong?

**Comment by bokub** [comment]
Can you please send a screenshot of the dialog where you configure the energy statistic and the price statistic?

**Comment by MaJerle** [comment]
OK you gave me thinking with this question. It was not set to `_cost` entity! Now it shows correctly.

**Comment by bokub** [comment]
That's what I expected 😅
