### ISSUE TITLE
Décalage des informations affichées par HA Linky et Enedis

### ISSUE THREAD

**Issue by chrnico2** [bokub/ha-linky#66]
Bonjour Boris,

Merci pour ce super dev !

J'ai un petit soucis d'incohérence entre les données Enedis et HA Linky. Sur Enedis les données de la conso horaire sont affichées par tranche d'une demi-heure, sur HA Linky par tranche d'une heure. Jusque là rien d'anormal. En revanche, si je somme les données des 2 demi-heures côté Enedis, je ne retrouve jamais le même total de KWh que HA Linky sur la même période d'une heure. Dans mon exemple ci-dessous sur la plage 2h-3h : Enedis = 1,38 + 0,7 = 2,08 ; HA Linky = 1,04. Comme si HA Linky n'affichait que la première demi-heure. Le total journalier est bon. donc je suppose que les données en entrée le sont aussi.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/f27126c9-0081-4877-abf1-f24cfc9d3b7d">

<img width="742" alt="image" src="https://github.com/user-attachments/assets/fdbe8420-9e1f-4673-be1f-dfc3d5a34ee3">

<img width="971" alt="image" src="https://github.com/user-attachments/assets/2b36e617-c943-438f-b5fd-1b38045d16f5">

<img width="715" alt="image" src="https://github.com/user-attachments/assets/f0c1f3bb-371c-4152-8eb2-815a7d88240e">

<img width="293" alt="image" src="https://github.com/user-attachments/assets/74989f69-7d22-402d-81da-4d97ba32a9eb">

**Comment by bokub** [comment]
Salut Christophe !

Ton erreur vient du fait que tu additionnes des kW, qui est une unité de puissance et non pas d'énergie (kWh) .

C'est comme si tu me disais "j'ai roulé 30 minutes à 60km/h puis 30 minutes à 40 km/h donc ça me fait 1h à 100km/h"

En réalité, en 1h, tu auras parcouru 50km, soit la moyenne des deux demi-heures

Ici c'est pareil, Enedis t'affiche la **puissance moyenne** sur la demi heure, alors que moi je t'affiche l'énergie consommée

Bonne journée !
