### ISSUE TITLE
Problème d'importation de fichier CSV

### ISSUE THREAD

**Issue by lebleu974** [bokub/ha-linky#67]
Le fichier récupéré sur enedis ne s'importe pas. Le dossier cf6b56a3_linky n'est pas créé dans le dossier addon_configs. J'ai donc suivi le tuto, j'ai donc créé le dossier cf6b56a3_linky et j'y ai déposé le fichier téléchargé sur Enedis et malheureusement le fichier n'est pas importé. Les données doivent-elle être importer dans le fichier statistic ?

Merci pour votre aide

**Comment by bokub** [comment]
Tout d'abord, bonjour

Peux-tu partager les logs qui s'affichent après avoir fait une remise à zéro ?

**Comment by lebleu974** [comment]
J'ai trouvé la réponse à mon problème. Ce n'était pas le bon dossier addon_configs.

Je vous remercie pour votre aide
