### ISSUE TITLE
Intensité max

### ISSUE THREAD

**Issue by SamLaeti** [bokub/ha-linky#68]
Bonjour, 
dans un premier temps merci pour ton travail !

Est-il possible de récupérer les valeurs de consommation maximum comme possible sur les appli de nos fournisseurs d’accès ?

**Comment by bokub** [comment]
Salut,

Non car ce n'est pas adapté au tableau de bord d'énergie de Home Assistant qui ne gère pas ce type de donnée (sauf erreur de ma part)

**Comment by SamLaeti** [comment]
Ok merci pour ton retour. Je vais essayer de trouver un moyen de l'adapter sur un autre tableau de bord.
