### ISSUE TITLE
Échec de l'obtention des journaux du module complémentaire, No systemd-journal-gatewayd Unix socket available

### ISSUE THREAD

**Issue by alaindaix13** [bokub/ha-linky#70]
Bonjour,
J'ai un soucis au lancement de HA-Linky. J'ai un message d'erreur lorsque je lance l'addon dans les journaux :
`Échec de l'obtention des journaux du module complémentaire, No systemd-journal-gatewayd Unix socket available`

Ce soucis semble provenir du supervisor mais je ne sais pas comment la résoudre : 
```
2024-09-07 19:15:45.675 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-09-07 19:16:48.388 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
2024-09-07 19:16:52.496 ERROR (MainThread) [supervisor.host.logs] No systemd-journal-gatewayd Unix socket available
```
J'ai fait le dernier update, mais cela ne change rien, je suis en version :
Core 2024.9.1
Supervisor 2024.08.0

Avez-vous une idée comment résoudre ce soucis?

D'avance merci de votre aide.

**Comment by bokub** [comment]
Salut,
Aucune idée car c'est un problème de ton système qui n'a rien à voir avec mon addon 

As-tu le même problème avec d'autres addons?

Si oui essaie de poster sur un forum home assistant pour trouver de l'aide 

Bonne soirée !

**Comment by alaindaix13** [comment]
Merci de te réponse, en effet, le soucis est lié au supervisor HA, je vais demander de l'aide sur un forum...

Bon dimanche

**Comment by alaindaix13** [comment]
Résolu en appliquant la commande apt install systemd-journal-remote --reinstall
