### ISSUE TITLE
Synchronisation des donnés 

### ISSUE THREAD

**Issue by Moha-maison** [bokub/ha-linky#71]
Bonjour,

Merci pour l'add- on est pour le travail réalisé 

J'ai une question, est-il possible de réaliser plusieurs synchronisation des consommation genre matin et soir voir plus si possible ? Sa serait bien de connaître l'évolution des consommations au fil de l'eau enfin presque au file de l'eau. 

Merci d'avance

**Comment by tgeorgel** [comment]
> Bonjour,
> 
> Merci pour l'add- on est pour le travail réalisé
> 
> J'ai une question, est-il possible de réaliser plusieurs synchronisation des consommation genre matin et soir voir plus si possible ? Sa serait bien de connaître l'évolution des consommations au fil de l'eau enfin presque au file de l'eau.
> 
> Merci d'avance

Le soucis c'est que l'API Enedis ne rend disponible la data que le jour suivant. Donc au minimum tu devra attendre le lendemain pour consulter la data du jour (quelle que soit l'heure). C'est une limitation de la part d'Enedis pour le coup.

A part cumuler la data du plugin avec une griffe de télécommunication à placer sur le Linky (par ex. Conso live de total energy ou un module lambda), tu ne pourra pas avoir de "temps réel".
