### ISSUE TITLE
Décalage des coûts 

### ISSUE THREAD

**Issue by benou2** [bokub/ha-linky#72]
Bonjour, 

Tout d'abord merci pour cet add-on. C'est vraiment du super travail 👍 

J'avoue que je sais pas trop si le problème se trouve entre la chaise et le clavier, mais les informations me semblent correctes. J'ai un décalage de résultat, celui-ci devrait être aux environs 64,45€ (hors abo) mais il est seulement de 58.22€. 

![image](https://github.com/user-attachments/assets/b2122869-75be-4908-91bd-3dd4d757a7e0)
![image](https://github.com/user-attachments/assets/a1615d60-b79b-47e6-9d72-8196af2ca3d6)

Voici mon planning HP vs HC : 
- price: 0.21
  before: "07:04"
- price: 0.27
  after: "07:04"
  before: "23:04"
- price: 0.21
  after: "23:04"

PS : je suis allé dans les stats dev, mais c'est un peu obscur pour moi.

Merci de votre aide  !

**Comment by bokub** [comment]
Hello,
Il faut que tu affiches ton graphique sur une seule journée (au lieu de tout le mois), puis que tu regardes sur une heure en particulier si le prix affiché correspond à ce que tu aurais calculé

**Comment by bokub** [comment]
Salut

T'a config m'a l'air correcte, mais je ne peux pas te dire ce qui ne va pas juste en regardant un graphique sur un mois entier

Va voir dans l'onglet statistiques des outils de développement, clique sur l'icône tout à droite, puis analyse une heure en particulier.

Le calcul est-il correct?

Ton hellowatt, c'est possible d'avoir un coût pour une seule journée? Si oui, as-tu essayé de refaire le calcul pour savoir si tu tombais sur la même valeur qu'eux?
