### ISSUE TITLE
Tableau de bord consommation de la veille

### ISSUE THREAD

**Issue by Nutiix** [bokub/ha-linky#74]
Bonjour,

Petite question qui j’espère ne va pas paraître stupide.
Lorsque mon tableau de bord affiche le graphique énergie, il affiche le graphique du jour, or mes données ne sont pas mises à jour à l’heure mais au jour.
Est ce qu’il est possible d’afficher sur le tableau de bord la consommation de la veille plutôt que celle du jour

Sinon, est il possible de récupérer les données du jour de la part d’enedis ?

Merci d’avance

**Comment by bokub** [comment]
Salut,

Je t'invite à relire la documentation, j'y ai écrit des explications qui répondent exactement à tes questions (en particulier le paragraphe "Bon à savoir"). Si ça n'est pas clair après relecture, n'hésite pas à me le dire et je clarifierai.

Quant au jour par défaut qui s'affiche dans ton dashboard énergie, je n'ai pas la réponse, et à vrai dire ça n'a pas grand chose à voir avec mon addon, c'est plutôt une question liée à Home Assistant 

Bonne soirée !
