### ISSUE TITLE
Image ha-linky introuvable sur docker hub

### ISSUE THREAD

**Issue by kwiky** [bokub/ha-linky#75]
J'ai l'impression que l'image docker `ha-linky` n'est plus disponible sur le hub de docker.
Est-ce que quelque chose a changé ?

**Comment by bokub** [comment]
Premièrement, bonjour,

Je n'ai jamais publié l'image sur docker hub, si tu l'as pull par le passé ça n'est pas une image créée par moi mais probablement par un utilisateur.

Je t'invite à relire le README, où tu trouveras la commande permettant de build une image adaptée à ton système

Bonne fin de journée !

**Comment by kwiky** [comment]
Oui bonjour 😅

OK, je vais voir ça
