### ISSUE TITLE
Demande d'évolution : Récupération des consommations de Gaz

### ISSUE THREAD

**Issue by Cyril56** [bokub/ha-linky#77]
Bonjour, 

Tout d'abord merci pour le développement de ce module qui répond entièrement à mes besoins ;). 
En cherchant un un peu et après avoir eu l'information auprès de GRDF que mon compteur de Gaz est lui aussi communiquant je me suis rendu compte que des API existent aussi pour suivre ce type de consommation : https://www.grdf.fr/entreprises/grdf-et-vous-au-quotidien/consommations-gaz/donnees-consommation-gaz-entreprises

Comme pour ENEDIS, il semble à première vue que seule les entreprises sont en mesure d'accéder aux API :( je m'interroge donc sur la faisabilité de faire évoluer le Plugin (voir de créer son petit frère) pour les consommation de GAZ.

Par avance merci d'avoir à minima pris le temps de lire ma demande.

**Comment by bokub** [comment]
Hello,

Alors je pense que ça n'a rien à faire dans cet add-on, et qu'il s'agirait plutôt d'un "petit frère" comme tu dis.

En effet, le fait qu'une API existe ne suffit pas comme critère pour rajouter des fonctionnalités à cette add-on que j'ai déjà suffisamment de mal à maintenir (alors que je l'utilise même pas moi même).
