### ISSUE TITLE
Coût de consommation qui semble mal calculé

### ISSUE THREAD

**Issue by emphyrioio** [bokub/ha-linky#78]
Bonjour,
Un grand merci pour ce super travail.
C'est peut-être une erreur de configuration de ma part, mais il me semble que le coût de ma consommation n'est pas calculé correctement.
J'ai spécifié le coût horaire de ma consommation (tarif unique) : 0,2516 € mais le total de ma consommation est calculé avec un coût de 1€. J'ai également essayé de mettre 0,25 € mais le résultat est le même. 
Voici ma configuration (j'ai flouté mes infos perso) : 
![image](https://github.com/user-attachments/assets/179cb6eb-4edb-4550-b62e-73da162c7168)
![image](https://github.com/user-attachments/assets/2d8b9b0e-a9ef-44f6-b878-4c65db8b86ca)
Et voici ce que je vois dans le tableau de bord énergie :
![image](https://github.com/user-attachments/assets/b509be8b-3134-482e-9438-db1bfc4a5ef5)
Encore merci !

**Comment by bokub** [comment]
Salut, 

Tu n'as pas bien configuré ton tableau de bord énergie 

Plus d'infos dans #65

**Comment by emphyrioio** [comment]
Effectivement, j'ai identifié le problème : l'entité n'apparaissait pas parce que j'ai ajouté le prix après avoir importé les données.
La chose étrange et que j'ai désintallé l'addon, effacté toutes les données et réinstallé sans que cela ne règle le problème. Mais je pense que ça c'est un problème qui vient de HA, qui prétend effacer les données mais ne doit pas réellement effacé le répertoire du volume correspondant. 
Finalement, je suis parvenu à régler le problème avec un reset. L'addon s'est alors mis à redémarrer et reset en boucle alors que le paramètre sync avait bien été remis dans la configuration (en tous cas il apparaissait dans l'UI). Du coup, j'ai réenregistré le configuration et redémarré l'addon et là il a refait la sync. J'ai le bon prix à présent. 👍

**Comment by bokub** [comment]
> Le reset semble bien une opération obligatoire pour pouvoir effectuer le calcul des coûts, au moins si on a installé à l'origine une version antérieure à la 1.5...

Oui en effet, d'ailleurs c'est documenté:

<img src="https://github.com/user-attachments/assets/a4b3a7b2-8add-45d9-8f5b-2e777f8e1bce" width="600"/>

> Question complémentaire : l'entité Linky (costs) n'est pas utilisable en dehors du panneau Energie?

Ce n'est pas une entité mais une statistique. Peut-être que tu peux utiliser une [statistics card](https://www.home-assistant.io/dashboards/statistic/) ?

**Comment by SAS-Malko** [comment]
Ce n'est pas une entité mais une statistique. Peut-être que tu peux utiliser une statistics card?

Merci, en effet ça fonctionne. 
Ce n'est pas encore comme je voudrais mais au moins ça affiche le coût :)

Pour l'entité j'avais lu un peu vite en effet. 
Du coup mon commentaire précédent n'est pas correct.
-> Je comprends maintenant que le reset est nécessaire ssi on veut connaître les coûts précédents la mise en oeuvre de la fonctionnalité de calcul des coûts, sinon on attend tout bêtement la synchronisation du lendemain.

Encore Merci
LB
