### ISSUE TITLE
Prix kwh non reconnu

### ISSUE THREAD

**Issue by pixelion8** [bokub/ha-linky#79]
Bonjour, 🤗
j'ai bien réussi à installer ha-linky via docker et il est parfaitement reconnu par home assistant. ❤️
j'ai juste un petit soucis pour le prix. Mon code est peut être pas bon dans le options.json car home assistant ne me liste pas "cost" dans suivi des couts totaux (afin que je puisse récupérer le prix du kwh).
Mon code
```  {
    "meters": [
      {
        "prm": "********",
        "token": "******",
        "name": "Consommation Linky",
        "action": "sync",
        "production": false
      }
    ],
    "costs": [
      {
        "price": 0.204088
      }
    ]
  }
  ```
ai-je fais une erreur dans mon code ? genre une virgule ou un truc du genre lol

**Comment by bokub** [comment]
Partager tes logs ça peut aider aussi

**Comment by pixelion8** [comment]
bien joué !
oui c'était ça. j'avais rajouté le prix après. J'ai donc suivi la procédure pour effacer les infos et resynchroniser, et la tout est bon.
Merci beaucoup pour ton travail.
Franchement c'est top
