### ISSUE TITLE
Intégration HACS

### ISSUE THREAD

**Issue by notready123** [bokub/ha-linky#81]
Bonjour,
Merci pour le travail. Mon home assistant est installé sur un docker et je n'ai donc pas accès aux modules complémentaires, est ce envisageable de l'ajouter au community store ?

**Comment by bokub** [comment]
Sauf erreur de ma part, il n'y a pas d'add-ons dans HACS

**Comment by notready123** [comment]
Ok ça marche merci pour ton retour, je vais faire l'installation manuellement dans ce cas
