### ISSUE TITLE
Impossible de faire fonctionner l'add on dans HA

### ISSUE THREAD

**Issue by Toug19** [bokub/ha-linky#83]
J'essaie en vain de faire fonctionner ha-linky avec mon Home Assistant.

J'ai activé la collecte de la consommation horaire:
![image](https://github.com/user-attachments/assets/78fa815c-23e7-4e41-9758-8e5e36a1c210)

J'ai créé le token et la page de test (https://conso.boris.sh/exemples/) arrive à récupérer les données de consommation journalière avec mon prm et token.

voici la configuration de ha-linky:
`
- prm: "231039073XXXXX"
  token: >-
    mon_token
  name: Linky consumption
  action: sync
  production: false
`
J'ai remplacé les 5 derniers chiffres par X et remplacé le token par "mon_token" (mais il ne devrait pas y avoir de probleme car j'ai fait des copier coller)

Voici le log du module:

[cf6b56a3_linky_2024-11-26T18-33-54.700Z.log](https://github.com/user-attachments/files/17924435/cf6b56a3_linky_2024-11-26T18-33-54.700Z.log)

Dans la configuration du panneau "Energie" de HA, j'ai mis Linky consumption dans la partie Consommation du réseau.

![image](https://github.com/user-attachments/assets/5c5a4f1f-8028-4b13-b444-bb3390215528)

Mais les données de consommation restent désespérément vides.

En fait je n'arrive pas à voir quelle entités est liée à ce module, voici ce que je trouve concernant Linky:
![image](https://github.com/user-attachments/assets/52ac9a74-515a-4d5e-919d-e084e11240ab)
Merci pour votre aide.

**Comment by bokub** [comment]
Salut,

Visiblement tout fonctionne, et ton log le confirme.

On peut avoir un screenshot de ton dashboard énergie sur le 24 ou 25 novembre ?

**Comment by Toug19** [comment]
Désolé, j'avais mal compris, je pensais que l'on pouvait avoir la consommation horaire en live. Effectivement si je remonte sur les jours précédents, je vois bien mes données.

**Comment by bokub** [comment]
Je t'invite à relire la documentation, tout y est expliqué avec beaucoup de précision !
