### ISSUE TITLE
Price

### ISSUE THREAD

**Issue by Qualif22** [bokub/ha-linky#86]
Bonjour

dans la configuration j’ai rajouter dans l’option costs la formule suivante : - price: 0,20
Et enregistrer 

malheureusement je désire supprimer cette ligne mais à chaque fois que j’enregistre j’ai une erreur et impossible à enlever.

pouvez vous me dire comment l’enlever ?
Merci

**Comment by Smilee95** [comment]
J'ai eu le même souci, il faut remplacer la , par un .
Donc mettre - price: 0.20
