### ISSUE TITLE
Import HA réussi mais pas de fichiers dans le répertoire

### ISSUE THREAD

**Issue by oldchap56** [bokub/ha-linky#88]
Je suis sur HAOS, toutes mises à jour faites.
J'ai installé l'add-on après avoir suivi la procédure.
Dans les logs a priori j'ai bien la liaison et l'import des données, mais après une nuit je n'ai toujours pas de consommation affichée dans le dashboard "Energie", et par ailleurs il n'y a aucun fichier CSV dans /addon_configs/cf6b56a3_linky
Merci à vous.

Voici lesderniers  logs : 
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
HA Linky is starting
Connection with Home Assistant established
PRM XXXXXXXXX found in configuration for consumption
[07/12 16:49] New PRM detected, historical consumption data import is starting
Found 0 CSV file in /addon_configs/cf6b56a3_linky
Successfully retrieved consumption load curve from 2024-11-30 to 2024-12-07
Successfully retrieved daily consumption data from 2024-06-04 to 2024-11-30
Successfully retrieved daily consumption data from 2023-12-08 to 2024-06-04
Data import returned 526 data points from 08/12/2023 to 06/12/2024
Data synchronization planned every day at 06:28:33 and 09:28:33
Connection with Home Assistant closed

**Comment by bokub** [comment]
Hello,

Est-ce que tu peux m'envoyer une capture d'écran de ton dashboard énergie sur la journée du 5 décembre ?

**Comment by oldchap56** [comment]
Hello,*
Voici en pièce jointe le fichier demandé (aucune donnée), ainsi que le
répertoire add-on linky.
Pour info comme il n'y avait pas de fichier dans le répertoire add-ons
linky, j'ai fait une extraction manuelle du fichier CSV chez Enedis et je
l'ai déposée dans ce répertoire.
Merci de ton aide.
Olivier
Nota : c'est le we peut être y a t-il des difficultés de synchro chez
Enedis comme d'habitude  ...

**Comment by oldchap56** [comment]
Pour info Conso API n'arrive pas non plus à télécharger les données du 5
décembre (alors qu'hier à l'initialisation ça marchait).
Bonne journée

**Comment by oldchap56** [comment]
Et la config Energie de HA (désolé je n'avais pas vu).

**Comment by bokub** [comment]
Je n'ai rien reçu, il faut que tu ajoutes tes fichiers sur GitHub par en envoyant des e-mails

**Comment by oldchap56** [comment]
Bonsoir,
J'ai progressé ! J'ai en effet récupérer chez Enedis un mois avec les
données horaires sous forme de fichier CSV;
Je l'ai uploadé dans le répertoire addons_linky, et les consommations
apparaissent bien dans le tdb Energie.
Peut-être les erreurs sont-elles dues à l'impossibilité de télécharger chez
Enedis samedi et dimanche (comme tous les we ou presque).
Je verrai bien si ça s'améliore la semaine prochaine.
Bonne soirée.
Olivier
[image: Consommation 5-12.png]

**Comment by bokub** [comment]
Salut,

Je ne comprends pas quel est ton problème ou de quelle erreur tu parles, j'ai l'impression que tout fonctionne bien mais tu as l'air de penser le contraire

**Comment by oldchap56** [comment]
Bonjour Boris,
Il n'y a plus de problème tout est réglé, il faut juste que je trouve les
bonnes variables pour pouvoir afficher les consommations heures creuses /
heures pleines, ça va le faire.
Merci encore de ta réactivité et surtout Bravo pour ce développement que tu
as fait (j'avais il y a quelques années interrogé Enedis qui malgré ses
milliards ne s'intéressait pas à ce développement !).
Bonne continuation, je suivrai les évolutions avec plaisir.
