### ISSUE TITLE
Calcul cout vs hello watt

### ISSUE THREAD

**Issue by vxav** [bokub/ha-linky#90]
Salut, 

Est-ce que de ton coté tu as une bonne corrélation entre les valeurs de ton fournisseur et l'intégration via l'API?

Je prend l'exemple du 13 Décembre ici. La conso totale est bonne des 2 cotés mais les graphs et le calcul de cout ne semblent pas correspondre.

> _EDIT: Je répond a ma question sur la forme du graph. Hello watt travaille par tranche de 30 minutes et HA par tranches d'une heure. La question du cout est toujours d'actu par contre._

Je me suis dit que cela pourrait venir du lissage de l'abonnement sur 30 jours mais ca ne reviendrait qu'à 0.55€ environ donc encore loin des 4.95€.

Les couts correspondent a ce que j'ai sur le site Hello Watt.

```json
      "costs": [
        {
          "price": 0.2014,
          "after": "06:00",
          "before": "22:00"
        },
        {
          "price": 0.1558,
          "after": "22:00",
          "before": "06:00"
        }
      ]
```

<img width="1599" alt="image" src="https://github.com/user-attachments/assets/6c3685f9-7a4d-4e53-8a0c-6aa809f3e386" />
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/57baa4b5-6c05-4538-ae59-8ef5a3e55b97" />

(d'ailleurs, je me suis dit que ca pourrait être interessant d'avoir un paramètre pour ajouter le cout mensuel de l'abonnement et le lisser sur chaque jour qu'en penses tu?)

**Comment by bokub** [comment]
Salut !

D'après ta configuration de coûts, tu ne paies ton électricité que entre 6h et 22h ? 

J'imagine que non donc je t'invite à relire les exemples de la documentation et à corriger le problème

**Comment by vxav** [comment]
Ca serait tellement bien!

je crois que je vois le probleme. Etrange comme systeme mais merci 🙂 

> N.B : Il faut configurer séparément la période minuit - 6h et la période 22h - minuit

**Comment by vxav** [comment]
J'ai fait un reset puis re-importé et maintenant c'est tout bon.

Je peux aussi confirmer avec une certaine certitude (pour pas dire 100%) que Hello Watt ajoute le prix de l'abonnement lissé sur le mois. Ce qui me parait pas mal comme idée pour connaire le prix exact. Par contre je ne sais pas si cela est possible dans le cadre de HA étant donné que ce n'est pas lié aux kwh.

**Comment by bokub** [comment]
> Etrange comme systeme

Oui ça peut paraître étrange mais c'est plus facile à interpréter: pour chaque point de donnée, je ne lis le coût que si l'heure est avant le "before" et après le "after" **pour la journée en cours**.

Dans le cas contraire, ça voudrait dire que 17h est "avant" 16h de la journée du lendemain, et que 6h est bien "après" 22h de la journée de la veille. Je trouve ça très étrange aussi comme système.

Pour l'histoire du coût de l'abonnement, il y a l'issue #63
